# ────────────────────────────── cloudbuild.yaml ──────────────────────────────
# Builds, pushes and deploys the FRONTEND container to Cloud Run (managed)
# Repo layout:
#   • ./frontend           (Dockerfile lives here)
# ──────────────────────────────────────────────────────────────────────────────
steps:
# 1) BUILD ─────────────────────────────────────────────────────────────────────
- id: Build FE image
  name: gcr.io/cloud-builders/docker
  dir: frontend                # build context = ./frontend
  args:
    [
      'build',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/ai-prompt-coach/frontend:$BUILD_ID',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/ai-prompt-coach/frontend:latest',
      '.'
    ]

# 2) PUSH ──────────────────────────────────────────────────────────────────────
- id: Push FE image ($BUILD_ID)
  name: gcr.io/cloud-builders/docker
  args: [ 'push',
          'us-central1-docker.pkg.dev/$PROJECT_ID/ai-prompt-coach/frontend:$BUILD_ID'
        ]

- id: Push FE image (latest)
  name: gcr.io/cloud-builders/docker
  args: [ 'push',
          'us-central1-docker.pkg.dev/$PROJECT_ID/ai-prompt-coach/frontend:latest'
        ]

# 3) DEPLOY ────────────────────────────────────────────────────────────────────
- id: Deploy to Cloud Run
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      'run','deploy','ai-prompt-coach-frontend',
      '--region','us-central1',
      '--image','us-central1-docker.pkg.dev/$PROJECT_ID/ai-prompt-coach/frontend:$BUILD_ID',
      '--platform','managed',
      '--allow-unauthenticated',
      '--port','8085'               # ← NEW: make Cloud Run listen on 8085
    ]

# List images for the Build History page
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/ai-prompt-coach/frontend:$BUILD_ID'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/ai-prompt-coach/frontend:latest'
