# ───────────────────────────────── cloudbuild.yaml ───────────────────────────
# Assumes this file sits in the repo root and the frontend source code
# (including Dockerfile) lives under ./frontend
steps:
# 1) BUILD  ───────────────────────────────────────────────────────────────────
- name: gcr.io/cloud-builders/docker
  id: Build FE image
  dir: frontend                 # run docker build *inside* the frontend folder
  args:
    [
      'build',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/ai-prompt-coach/frontend:$SHORT_SHA',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/ai-prompt-coach/frontend:latest',
      '.'
    ]

# 2) PUSH  ────────────────────────────────────────────────────────────────────
- name: gcr.io/cloud-builders/docker
  id: Push FE image ($SHORT_SHA)
  args: [
    'push',
    'us-central1-docker.pkg.dev/$PROJECT_ID/ai-prompt-coach/frontend:$SHORT_SHA'
  ]

- name: gcr.io/cloud-builders/docker
  id: Push FE image (latest)
  args: [
    'push',
    'us-central1-docker.pkg.dev/$PROJECT_ID/ai-prompt-coach/frontend:latest'
  ]

# 3) DEPLOY ───────────────────────────────────────────────────────────────────
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  id: Deploy to Cloud Run
  entrypoint: gcloud
  args:
    [
      'run','deploy','ai-prompt-coach-frontend',
      '--region','us-central1',
      '--image','us-central1-docker.pkg.dev/$PROJECT_ID/ai-prompt-coach/frontend:$SHORT_SHA',
      '--platform','managed',
      '--allow-unauthenticated'
    ]

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/ai-prompt-coach/frontend:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/ai-prompt-coach/frontend:latest'
